# Generated by Django 3.2.6 on 2021-08-08 15:16

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('my_image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile/images')),
                ('rating', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
