# Generated by Django 3.2.6 on 2021-08-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_image'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='my_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='introduction',
        ),
        migrations.AddField(
            model_name='profile',
            name='post_participated',
            field=models.ManyToManyField(blank=True, related_name='post_participated_profile', to='main.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
