# Generated by Django 3.2.6 on 2021-08-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
