# Generated by Django 3.2.6 on 2021-08-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Offline', '오프라인'), ('Online', '온라인'), ('Delivery', '배달음식')], max_length=20),
        ),
    ]
