# Generated by Django 3.2.6 on 2021-08-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
