# Generated by Django 3.2.6 on 2021-08-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210806_1438'),
        ('main', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_post', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members_post', to='accounts.Profile'),
        ),
    ]
