# Generated by Django 3.2.6 on 2021-08-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210806_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('where', models.CharField(max_length=200)),
                ('payment', models.CharField(max_length=50)),
                ('how', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=400, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
    ]
