# Generated by Django 3.2.6 on 2021-08-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
